// <auto-generated />
namespace BussinessInfo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class big_update_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(big_update_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201906190711394_big_update_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
