// <auto-generated />
namespace BussinessInfo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_DMDiaBan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_DMDiaBan));
        
        string IMigrationMetadata.Id
        {
            get { return "201906170950310_update_DMDiaBan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
